version: "3.9"
name: "sie-docker-database"

services:
  sql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sie-mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=ul1m4@2024$1
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - ./sie-database:/var/opt/mssql/data