USE STAGE_VENTAS;

CREATE TABLE DIM_CLIENTE (
    PK_CLIENTE INT IDENTITY NOT NULL,
    NOMBRE VARCHAR(120),
    DNI VARCHAR(8),
    FEC_CREACION DATE,
    USU_CREACION VARCHAR(50)
);

CREATE TABLE DIM_PROMOTOR (
    PK_PROMOTOR INT IDENTITY NOT NULL,
    PROMOTR VARCHAR(50),
    FEC_CREACION DATE,
    USU_CREACION VARCHAR(50)
);

CREATE TABLE DIM_CATEGORIA (
    PK_CATEGORIA INT IDENTITY NOT NULL,
    CATEGORIA VARCHAR(50),
    FEC_CREACION DATE,
    USU_CREACION VARCHAR(50)
);

CREATE TABLE DIM_TIPOPAGO (
    PK_TIPOPAGO INT IDENTITY NOT NULL,
    TIPOPAGO VARCHAR(20),
    FEC_CREACION DATE,
    USU_CREACION VARCHAR(50)
);

CREATE TABLE DIM_FECHA (
	PK_FECHA INT NOT NULL,
	FECHA DATE NULL,
	ANHO smallint NOT NULL,
	MES smallint NOT NULL,
	DIA smallint NOT NULL,
	NOMBRE_MES varchar(20) NULL,
	NOMBRE_DIA varchar(20) NULL,
	FEC_CREACION DATE,
    USU_CREACION VARCHAR(50)
)

CREATE TABLE DIM_HORA (
	PK_HORA varchar(6) UNIQUE NOT NULL,
	MINUTO time NOT NULL,
	HORA24 smallint NOT NULL,
	PARTE_DEL_DIA varchar(8),
	FEC_CREACION DATE,
    USU_CREACION VARCHAR(50)
)

---

CREATE TABLE FACT_VENTAS (
    PK_VENTA INT IDENTITY NOT NULL,
    PK_CLIENTE INT,
	PK_PROMOTOR INT,
	PK_CATEGORIA INT,
	PK_TIPOPAGO INT,
	PK_EMPLEADO INT,
	PK_FECHA INT,
	PK_HORA INT,
	MONTO INT,

    FEC_CREACION DATE,
    USU_CREACION VARCHAR(50)
);