USE master;
go

IF( EXISTS ( SELECT name FROM master.sys.databases WHERE name = 'STAGE_VENTAS' ) )
BEGIN
	DROP DATABASE STAGE_VENTAS;
END;
go

CREATE DATABASE STAGE_VENTAS;
go

USE STAGE_VENTAS;
go

CREATE TABLE DIM_CLIENTE (
    PK_CLIENTE INT IDENTITY NOT NULL,
    DNI VARCHAR(8) NOT NULL,
    NOMBRE VARCHAR(99),
    FEC_CREACION DATE,
    USU_CREACION VARCHAR(50)

    CONSTRAINT UNIQUE_DNI UNIQUE(DNI)
);

CREATE TABLE DIM_PROMOTOR (
    PK_PROMOTOR INT IDENTITY NOT NULL,
    PROMOTOR VARCHAR(50) NOT NULL,
    FEC_CREACION DATE,
    USU_CREACION VARCHAR(50)

    CONSTRAINT UNIQUE_PROMOTOR UNIQUE(PROMOTOR)
);

CREATE TABLE DIM_CATEGORIA (
    PK_CATEGORIA INT IDENTITY NOT NULL,
    CATEGORIA VARCHAR(50) NOT NULL,
    FEC_CREACION DATE,
    USU_CREACION VARCHAR(50)

    CONSTRAINT UNIQUE_CATEGORIA UNIQUE(CATEGORIA)
);

CREATE TABLE DIM_TIPOPAGO (
    PK_TIPOPAGO INT IDENTITY NOT NULL,
    TIPOPAGO VARCHAR(20) NOT NULL,
    FEC_CREACION DATE,
    USU_CREACION VARCHAR(50)

    CONSTRAINT UNIQUE_TIPOPAGO UNIQUE(TIPOPAGO)
);

CREATE TABLE DIM_LOCAL (
    PK_LOCAL INT IDENTITY NOT NULL,
    UBICACION VARCHAR(20) NOT NULL,
    FEC_CREACION DATE,
    USU_CREACION VARCHAR(50)

    CONSTRAINT UNIQUE_UBICACION UNIQUE(UBICACION)
);

-- data mock
INSERT INTO DIM_LOCAL(UBICACION) VALUES ('Callao')
INSERT INTO DIM_LOCAL(UBICACION) VALUES ('Ventanilla')
INSERT INTO DIM_LOCAL(UBICACION) VALUES ('Rimac')

CREATE TABLE DIM_FECHA (
	PK_FECHA VARCHAR(8) NOT NULL,
	FECHA DATE NULL,
	ANHO smallint NOT NULL,
	MES smallint NOT NULL,
	DIA smallint NOT NULL,
	NOMBRE_MES varchar(20) NULL,
	NOMBRE_DIA varchar(20) NULL,
	FEC_CREACION DATE,
    USU_CREACION VARCHAR(50)
)

CREATE TABLE DIM_HORA (
	PK_HORA varchar(6) UNIQUE NOT NULL,
	MINUTO time NOT NULL,
	HORA24 smallint NOT NULL,
	PARTE_DEL_DIA varchar(8),
	FEC_CREACION DATE,
    USU_CREACION VARCHAR(50)
)

---

CREATE TABLE FACT_VENTAS (
    PK_VENTA INT IDENTITY NOT NULL,
	PK_LOCAL INT,
    PK_CLIENTE INT,
	PK_PROMOTOR INT,
	PK_CATEGORIA INT,
	PK_TIPOPAGO INT,
	PK_FECHA INT,
	PK_HORA_INICIO VARCHAR(6),
	PK_HORA_FIN VARCHAR(6),
	MONTO DECIMAL(6,2),

    FEC_CREACION DATE,
    USU_CREACION VARCHAR(50)
);